#!/usr/bin/env python3
# XPSemu: builds Mozilla's certificate list (ps5/cacert.pem, from
# https://curl.se/ca/cacert.pem) into the app as ui/xui/cover-cacert.h, for
# HTTPS downloads (the PS5 has no certificate store curl can use). Run again
# after updating cacert.pem.
#
# Usage: ps5/embed-cacert.py   (from the xemu tree)
import os

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, '..'))
data = open(os.path.join(here, 'cacert.pem'), 'rb').read()
assert b'BEGIN CERTIFICATE' in data
out = ['// Generated by ps5/embed-cacert.py: do not edit.', '#pragma once', '',
       '// Mozilla\'s CA certificates (PEM), NUL-terminated.',
       f'static const unsigned char kCoverCaCerts[{len(data) + 1}] = {{']
for i in range(0, len(data), 20):
    out.append('    ' + ', '.join(str(b) for b in data[i:i + 20]) + ',')
out += ['    0', '};', '']
with open(os.path.join(root, 'ui', 'xui', 'cover-cacert.h'), 'w') as f:
    f.write('\n'.join(out))
print('embedded', data.count(b'BEGIN CERTIFICATE'), 'certificates,',
      len(data) // 1024, 'KB')
