#!/usr/bin/env python3
# XPSemu: the blank Xbox hard disk XPSemu makes when there's none
# (/data/xemu/xbox_hdd.qcow2): xemu-dashboard's image (MIT, Ryzee119 and
# contributors: github.com/xemu-project/xemu-dashboard; licence in
# ps5/blank-hdd/LICENSE), an 8 GB disk formatted as an Xbox's (C, E and the
# X/Y/Z caches) with a small free dashboard, no Microsoft files. Embedded
# zlib-compressed as ui/xui/blank-hdd.h. Run again after replacing
# ps5/blank-hdd/xbox_hdd.qcow2.
import hashlib
import os
import zlib

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, '..'))
data = open(os.path.join(here, 'blank-hdd', 'xbox_hdd.qcow2'), 'rb').read()
assert data[:4] == b'QFI\xfb', 'not a qcow2 image'
packed = zlib.compress(data, 9)
out = ['// Generated by ps5/embed-blank-hdd.py: do not edit.',
       '// xemu-dashboard\'s blank Xbox hard disk (MIT licence: '
       'ps5/blank-hdd/LICENSE),',
       f'// sha256 {hashlib.sha256(data).hexdigest()}.',
       '#pragma once', '',
       f'#define XPS_BLANK_HDD_SIZE {len(data)}',
       f'static const unsigned char kBlankHddZ[{len(packed)}] = {{']
for i in range(0, len(packed), 24):
    out.append('    ' + ','.join(str(b) for b in packed[i:i + 24]) + ',')
out += ['};', '']
with open(os.path.join(root, 'ui', 'xui', 'blank-hdd.h'), 'w',
          encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(out))
print(f'blank HDD: {len(data)} bytes, {len(packed)} packed')
