#!/usr/bin/env python3
# XPSemu: the names of libretro-thumbnails' Xbox box art (the second place
# covers come from, by name, when xdb has none for a title ID), from GitHub,
# into ps5/libretro-xbox-boxarts.txt and ui/xui/cover-libretro-index.h.
#
# Usage: ps5/make-libretro-index.py   (from the xemu tree; needs the internet)
import json
import os
import urllib.request

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, '..'))
url = ('https://api.github.com/repos/libretro-thumbnails/Microsoft_-_Xbox/'
       'git/trees/master?recursive=1')
tree = json.load(urllib.request.urlopen(url))['tree']
names = sorted(p['path'][len('Named_Boxarts/'):-len('.png')] for p in tree
               if p['path'].startswith('Named_Boxarts/') and
               p['path'].endswith('.png'))
with open(os.path.join(here, 'libretro-xbox-boxarts.txt'), 'w',
          encoding='utf-8') as f:
    f.write('\n'.join(names) + '\n')


def c_string(s):
    out = ''
    for ch in s.encode('utf-8'):
        out += '\\"' if ch == 34 else '\\\\' if ch == 92 else (
            chr(ch) if 32 <= ch < 127 else f'\\{ch:03o}')
    return '"' + out + '"'


lines = ['// Generated by ps5/make-libretro-index.py: do not edit.', '#pragma once',
         '', '// libretro-thumbnails/Microsoft_-_Xbox: Named_Boxarts/<name>.png',
         'static const char *const kLibretroXbox[] = {']
lines += [f'    {c_string(n)},' for n in names]
lines += ['};', '']
with open(os.path.join(root, 'ui', 'xui', 'cover-libretro-index.h'), 'w',
          encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(len(names), 'names')
