#!/usr/bin/env python3
# XPSemu: the Patch Store's list of Jay's Magic Patches
# (github.com/JayYardley/Xbox-Magic-Patches-by-Jay): every .JMP's title IDs,
# category, region, author and notes, read from their headers, into
# ps5/patch-catalog.tsv and ui/xui/patch-catalog.h. The files themselves are
# downloaded by the app when wanted.
#
# Usage: ps5/make-patch-catalog.py   (from the xemu tree; needs the internet)
import concurrent.futures
import json
import os
import re
import urllib.parse
import urllib.request

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, '..'))
repo = 'JayYardley/Xbox-Magic-Patches-by-Jay'
tree = json.load(urllib.request.urlopen(
    f'https://api.github.com/repos/{repo}/git/trees/main?recursive=1'))['tree']
paths = sorted(p['path'] for p in tree
               if p['type'] == 'blob' and p['path'].lower().endswith('.jmp'))


def header(path):
    url = (f'https://raw.githubusercontent.com/{repo}/main/' +
           urllib.parse.quote(path))
    text = urllib.request.urlopen(url, timeout=60).read().decode('utf-8', 'replace')
    info = {}
    for line in text.splitlines()[:40]:
        m = re.match(r'\s*([a-z-]+)\s*=\s*(.*)', line)
        if m and m.group(1) not in info:
            info[m.group(1)] = m.group(2).strip()
    ids = re.findall(r'\b[0-9A-Fa-f]{8}\b', info.get('version', ''))
    name = os.path.basename(path)
    cat = re.search(r'\{([^}]*)\}', name)
    return {
        'path': path,
        'ids': ','.join(i.upper() for i in ids),
        'title': info.get('game-title', name.split(' {')[0]),
        'category': cat.group(1).strip() if cat else 'Misc',
        'region': info.get('region', ''),
        'author': info.get('author', path.split('/')[0]),
        'notes': info.get('notes', '')[:200],
    }


with concurrent.futures.ThreadPoolExecutor(16) as pool:
    entries = [e for e in pool.map(header, paths) if e['ids']]

with open(os.path.join(here, 'patch-catalog.tsv'), 'w', encoding='utf-8') as f:
    for e in entries:
        f.write('\t'.join(e[k] for k in ('ids', 'category', 'region', 'author',
                                         'title', 'path', 'notes')) + '\n')


def c(s):
    out = ''
    for ch in s.encode('utf-8'):
        out += '\\"' if ch == 34 else '\\\\' if ch == 92 else (
            chr(ch) if 32 <= ch < 127 else f'\\{ch:03o}')
    return '"' + out + '"'


lines = ['// Generated by ps5/make-patch-catalog.py: do not edit.', '#pragma once',
         '', '// Jay\'s Magic Patches (github.com/JayYardley/'
         'Xbox-Magic-Patches-by-Jay), by title ID.',
         'struct PatchCatalogEntry {',
         '    const char *ids, *category, *region, *author, *title, *path, *notes;',
         '};', 'static const PatchCatalogEntry kPatchCatalog[] = {']
for e in entries:
    lines.append('    { ' + ', '.join(c(e[k]) for k in (
        'ids', 'category', 'region', 'author', 'title', 'path', 'notes')) + ' },')
lines += ['};', '']
with open(os.path.join(root, 'ui', 'xui', 'patch-catalog.h'), 'w',
          encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(len(entries), 'patches with title IDs, of', len(paths))
