#!/usr/bin/env python3
# XPSemu: the LaunchBox Games Database's pictures of Xbox games for the
# shortcuts' home-screen backgrounds, as ui/xui/launchbox-index.h: each
# game's names (its own and alternates) with its background art ("Fanart -
# Background"), or else its biggest HD screenshot (1280x720 at least; most
# are the Xbox's 640x480, too small). Files are at
# https://images.launchbox-app.com/<file>.
#
# Usage: ps5/make-launchbox-index.py Metadata.zip [sizes.tsv]
#        (from the xemu tree; https://gamesdb.launchbox-app.com/Metadata.zip;
#        sizes.tsv: DatabaseID, type, file, width, height of screenshots)
import os
import sys
import zipfile
import xml.etree.ElementTree as ET

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, '..'))
z = zipfile.ZipFile(sys.argv[1])

games = {}  # DatabaseID -> [names]
alts = []   # (DatabaseID, name)
images = {} # DatabaseID -> type -> [(rank, file)]
GOOD_REGIONS = {'', 'north america', 'united states', 'world'}
TYPES = {'Fanart - Background'}


def text(el, tag):
    return (el.findtext(tag) or '').strip()


for _, el in ET.iterparse(z.open('Metadata.xml')):
    if el.tag == 'Game':
        if text(el, 'Platform') == 'Microsoft Xbox':
            games[text(el, 'DatabaseID')] = [text(el, 'Name')]
        el.clear()
    elif el.tag == 'GameAlternateName':
        alts.append((text(el, 'DatabaseID'), text(el, 'AlternateName')))
        el.clear()
    elif el.tag == 'GameImage':
        kind = text(el, 'Type')
        if kind in TYPES:
            region = text(el, 'Region').lower()
            images.setdefault(text(el, 'DatabaseID'), {}).setdefault(
                kind, []).append((0 if region in GOOD_REGIONS else 1,
                                  text(el, 'FileName')))
        el.clear()

hd = {} # DatabaseID -> (area, file): the biggest HD screenshot
if len(sys.argv) > 2:
    for line in open(sys.argv[2]):
        gid, kind, file, w, h = line.rstrip('\n').split('\t')
        w, h = int(w), int(h)
        if kind.startswith('Screenshot') and w >= 1280 and h >= 720:
            if w * h > hd.get(gid, (0, ''))[0]:
                hd[gid] = (w * h, file)

for gid, name in alts:
    if gid in games and name and name not in games[gid]:
        games[gid].append(name)


def best(gid, kind):
    found = images.get(gid, {}).get(kind)
    return sorted(found)[0][1] if found else ''


entries = []
art_games = shot_games = 0
for gid, names in games.items():
    pic = best(gid, 'Fanart - Background')
    if pic:
        art_games += 1
    elif gid in hd:
        pic = hd[gid][1]
        shot_games += 1
    else:
        continue
    for n in names:
        entries.append((n, pic))
entries.sort()


def c(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


out = ['// Generated by ps5/make-launchbox-index.py: do not edit.',
       '#pragma once', '',
       '// LaunchBox Games Database, Microsoft Xbox: a game name and its',
       '// background art or HD screenshot (images.launchbox-app.com/<file>).',
       'static const struct { const char *name, *file; } kLaunchboxXbox[] = {']
out += [f'    {{ {c(n)}, {c(f)} }},' for n, f in entries]
out += ['};', '']
with open(os.path.join(root, 'ui', 'xui', 'launchbox-index.h'), 'w',
          encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(out))
print(f'{art_games} games with art, {shot_games} with an HD screenshot, '
      f'{len(entries)} names')
