#!/usr/bin/env python3
# XPSemu: the startup animation's emblem (the app icon's green X, from
# make-art.py, on transparency) built into the app as ui/xui/boot-logo.h.
#
# Usage: ps5/art/make-boot-logo.py   (from the xemu tree)
import importlib.util
import io
import os
import sys
import tempfile

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, '..', '..'))
# make-art.py draws all its art when loaded: let it, into a throwaway folder.
with tempfile.TemporaryDirectory() as scratch:
    argv, sys.argv = sys.argv, [sys.argv[0], scratch]
    spec = importlib.util.spec_from_file_location(
        'make_art', os.path.join(here, 'make-art.py'))
    art = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(art)
    sys.argv = argv

png = io.BytesIO()
art.emblem(512).save(png, 'PNG', optimize=True)
data = png.getvalue()
out = ['// Generated by ps5/art/make-boot-logo.py: do not edit.', '#pragma once',
       '', '// The XPSemu emblem, 512x512 RGBA PNG.',
       f'static const unsigned char kBootLogoPng[{len(data)}] = {{']
for i in range(0, len(data), 20):
    out.append('    ' + ', '.join(str(b) for b in data[i:i + 20]) + ',')
out += ['};', '']
with open(os.path.join(root, 'ui', 'xui', 'boot-logo.h'), 'w') as f:
    f.write('\n'.join(out))
print('emblem', len(data) // 1024, 'KB')
