#!/usr/bin/env python3
# XPSemu: embeds the dashboard's recorded sounds (ps5/sounds/<name>.wav) in
# the app as ui/xui/ui-sounds-data.h. Sounds without a file here are
# synthesized by ui-sounds.cc. Run again after changing a file.
#
# Usage: ps5/sounds/embed-sounds.py   (from the xemu tree)
import os

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, '..', '..'))
names = ['move', 'change', 'select', 'back', 'open', 'launch', 'error',
         'notify', 'startup', 'flash']

out = ['// Generated by ps5/sounds/embed-sounds.py: do not edit.',
       '#pragma once', '#include <stddef.h>', '']
table = []
for name in names:
    path = os.path.join(here, name + '.wav')
    if not os.path.exists(path):
        table.append('    { NULL, 0 },')
        continue
    data = open(path, 'rb').read()
    out.append(f'static const unsigned char kSound_{name}[{len(data)}] = {{')
    for i in range(0, len(data), 20):
        out.append('    ' + ', '.join(str(b) for b in data[i:i + 20]) + ',')
    out.append('};')
    table.append(f'    {{ kSound_{name}, sizeof(kSound_{name}) }},')

# The dashboard's music, on its own (not a UiSound).
music = os.path.join(here, 'music.wav')
if os.path.exists(music):
    data = open(music, 'rb').read()
    out.append('#define XPS_EMBEDDED_MUSIC 1')
    out.append(f'static const unsigned char kSound_music[{len(data)}] = {{')
    for i in range(0, len(data), 20):
        out.append('    ' + ', '.join(str(b) for b in data[i:i + 20]) + ',')
    out.append('};')

out += ['', '// By UiSound, in its order.',
        'static const struct { const unsigned char *data; size_t size; }',
        'kEmbeddedSounds[] = {'] + table + ['};', '']
with open(os.path.join(root, 'ui', 'xui', 'ui-sounds-data.h'), 'w') as f:
    f.write('\n'.join(out))
print('embedded:', ', '.join(n for n in names
                             if os.path.exists(os.path.join(here, n + '.wav'))))
